languageCode: zh
defaultContentLanguage: zh
defaultContentLanguageInSubdir: false
hasCJKLanguage: true
timeZone: Asia/Shanghai

theme: ananke

baseURL: http://ixtwuko.github.io/
title: Easy Easy
copyright: &copy 2022 施工中

summaryLength: 75